6.x compatible with php8.0
ruflin/Elastica pull request #1977
Opened 2021-09-10 10:12 UTC by AskaoAhmedSaad

make version 6.x compatible with php8.0

2021-09-13 06:19 UTC, ruflin reviewed
@AskaoAhmedSaad It would be nice if we could make 6.x compatible with PHP 8.0 but we should not make it a breaking change for existing users. Any ideas on how we can make it non breaking? I remember we had similar challenges with other PHP versions and reserved terms. Can you check it how we have solved it in other places / PR?

2021-09-13 06:19 UTC, ruflin commented on lib/Elastica/Query/Match.php
> -<?php
This looks like a breaking change?

2021-09-22 14:46 UTC, reedy commented
I was going to try and make a similar patch...

Don't remove the `Match` class; if it exists and isn't executed, it won't be a problem for PHP 8.0

Swap `Match` and `MatchQuery` around (so the `Match` alias extends `MatchQuery` instead of the other way around), and then update documentation.

If people are still using `Match` as the canonical in their own code, they'll need to update that to work on PHP 8.0 anyway, so that's not a problem. Anyone still using `Match` and not needing to support PHP 8.0 doens't need to make any changes

2021-09-22 14:50 UTC, reedy requested changes

2021-09-22 14:50 UTC, reedy commented on composer.json
> +        "php": "^7.0 | ^8.0",
Use `||` as per https://github.com/ruflin/Elastica/blob/master/composer.json#L18 for consistency

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/Match.php
> -class Match extends AbstractQuery
This should become `class Match extends MatchQuery` and otherwise be empty of content

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MatchNone.php
> + * MatchQuery none query. Returns no results.
This shouldn't be replaced. See master https://github.com/ruflin/Elastica/blob/master/src/Query/MatchNone.php#L6

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MatchAll.php
> + * MatchQuery all query. Returns all results.
This shouldn't be replaced.

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MatchPhrase.php
> + * MatchQuery Phrase query.
This shouldn't be replaced.

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MatchPhrasePrefix.php
> + * MatchQuery Phrase Prefix query.
This shouldn't be replaced.

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MatchQuery.php
> + * MatchQuery query.
This shouldn't be replaced.

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MatchQuery.php
> + * @deprecated since version 6.1.2, use the MatchQuery class instead.
This is incorrect, it's not deprecated.

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MultiMatch.php
> + * Multi MatchQuery.
This shouldn't be replaced.

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MultiMatch.php
> +     * Sets operator for MatchQuery Query.
This shouldn't be replaced.

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MultiMatch.php
> +     * Set field minimum should match for MatchQuery Query.
This shouldn't be replaced.

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MultiMatch.php
> +     * Set zero terms query for MatchQuery Query.
This shouldn't be replaced.

2021-09-22 14:50 UTC, reedy commented on lib/Elastica/Query/MultiMatch.php
> +     * Set cutoff frequency for MatchQuery Query.
This shouldn't be replaced.

2021-09-22 14:50 UTC, reedy commented on test/Elastica/Query/PercolateTest.php
> +        //MatchQuery a document to the registered percolator queries:
This shouldn't be replaced.

2021-09-22 14:52 UTC, reedy commented
Looks like this has just been done as a literal find and replace. Only really the code uses of the `Match` query needed updating. Replacing most (all?) of the `Match` comments with `MatchQuery` make no sense and don't align with what's on master.

2021-09-22 14:52 UTC, reedy commented on lib/Elastica/Query/Match.php
> -<?php
It definitely is :)

2021-09-22 14:55 UTC, reedy commented on lib/Elastica/Query/Match.php
> -class Match extends AbstractQuery
Keeping the comments above too, of course.

2021-09-22 15:37 UTC, AskaoAhmedSaad commented
@reedy @ruflin having a class with the name "Match" gives a parser error at PHP 8 environment, do you have a suggestion to overcome this and at the same time not to break the other PHP versions ?

I think maybe we can have a special version name with removing Match class totally and replace it with MatchQuery

2021-09-22 15:53 UTC, reedy commented
> @reedy @ruflin having a class with the name "Match" gives a parser error at PHP 8 environment, do you have a suggestion to overcome this and at the same time not to break the other PHP versions ?
> 
> I think maybe we can have a special version name with removing Match class totally and replace it with MatchQuery

It should only error if you execute the file using it (or lint it etc)... What are you doing to cause/see that error?

2021-09-23 03:51 UTC, reedy commented
I re-made your commit without the comment changes in https://github.com/reedy/Elastica/tree/6xphp8

composer.json:
```
{
	"require": {
		"ruflin/elastica": "dev-6xphp8 as 6.2"
	},
	"repositories": [
		{
			"type": "git",
			"url": "https://github.com/reedy/elastica.git"
		}
	]
}
```

Test PHP script:
```
<?php

require __DIR__ . '/vendor/autoload.php';

use Elastica\Query\MatchQuery;

$mq = new MatchQuery();
echo "Done\n";
```

Run it

```
reedy@MacBook-Pro elasticatest % php --version    
PHP 8.0.10 (cli) (built: Aug 26 2021 15:36:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.10, Copyright (c), by Zend Technologies
reedy@MacBook-Pro elasticatest % php test.php 
Done
```

2021-09-23 05:56 UTC, reedy commented
CI seems fine with the `Match` class existing too...

I've got https://github.com/ruflin/Elastica/pull/1981 to the point where I'm just fiddling with fixing up some minor test breakages (function calls that need updating)

2021-09-23 06:48 UTC, ruflin commented
As https://github.com/ruflin/Elastica/pull/1981 goes more into the direction we want to go I'm going to close this PR for now. @AskaoAhmedSaad Thanks for kicking this off and I would appreciate if you could chime in on https://github.com/ruflin/Elastica/pull/1981 In case we change direction, we can still reopen this one.

2021-09-23 06:48 UTC, closed without merging