Add 6.x (>= 6.2.0) supports PHP 8.0
ruflin/Elastica pull request #1989
Opened 2021-10-08 14:31 UTC by reedy

Not sure if anyone really minds how we want to denote the 6.x releases before 6.2. Happy to change to match.

Will cherry pick into 7.x and 6.x when it's decided (and this lands in master)

2021-10-08 16:21 UTC, thePanz requested changes
What about mentioning from which version the support of PHP 8.x is provided?

2021-10-11 15:00 UTC, ruflin commented
We could go so far to just state 5.x and older are unmaintained. Like this we don't need to keep the list of all the old releases? 2 tables also sounds finde to me.

2021-10-25 07:17 UTC, ruflin reviewed
Current changes LGTM and +1 on the propose changes to rename to branches.

2021-10-27 07:57 UTC, thePanz approved these changes

2021-10-27 08:00 UTC, merged